  dependencies:
      infrastructure-creator: 1.9.0
      consumer-service: 1.9.0
      data-structure-handler: 1.9.0
      custom-class-checker: 1.9.0
      hot-backup-service: 1.9.0
      metric-consumer: 1.9.0
      health-service: 1.9.0
      replication-service: 1.9.0
      diagnostic-service: 1.9.0
