  dependencies:
      infrastructure-creator: 2.0.0-rc.1
      consumer-service: 2.0.0-rc.1
      data-structure-handler: 2.0.0-rc.1
      custom-class-checker: 2.0.0-rc.1
      hot-backup-service: 2.0.0-rc.1
      metric-consumer: 2.0.0-rc.1
      health-service: 2.0.0-rc.1
      replication-service: 2.0.0-rc.1
      diagnostic-service: 2.0.0-rc.1
