  dependencies:
      infrastructure-creator: 0.2.4-rc.1
      consumer-service: 0.2.4-rc.1
      data-structure-handler: 0.2.4-rc.1
      custom-class-checker: 0.2.4-rc.1
      hot-backup-service: 0.2.4-rc.1
      metric-consumer: 0.2.4-rc.1
      health-service: 0.2.4-rc.1
      replication-service: 0.2.4-rc.1
      diagnostic-service: 0.2.4-rc.1
