  dependencies:
      infrastructure-creator: 2.0.0
      consumer-service: 2.0.0
      data-structure-handler: 2.0.0
      custom-class-checker: 2.0.0
      hot-backup-service: 2.0.0
      metric-consumer: 2.0.0
      health-service: 2.0.0
      replication-service: 2.0.0
      diagnostic-service: 2.0.0
