  dependencies:
      infrastructure-creator: 1.18.7
      consumer-service: 1.18.7
      data-structure-handler: 1.18.7
      custom-class-checker: 1.18.7
      hot-backup-service: 1.18.7
      metric-consumer: 1.18.7
      health-service: 1.18.7
      replication-service: 1.18.7
      diagnostic-service: 1.18.7
