  dependencies:
      infrastructure-creator: 
      consumer-service: 
      data-structure-handler: 
      custom-class-checker: 
      hot-backup-service: 
      metric-consumer: 
      health-service: 
      replication-service: 
      diagnostic-service: 
