name: "Draft new release"

env:
  git_user: 'SRE Automation'
  git_email: 'sre-team@hazelcast.com'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of next release'
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.1.0
        with:
          version: ${{ github.event.inputs.version }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "${{ env.git_user }}"
          git config user.email ${{ env.git_email }}

      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add CHANGELOG.md
          git commit --message "Prepare release ${{ github.event.inputs.version }}"

          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push changes
        run: git push origin release/${{ github.event.inputs.version }}

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Release version ${{ github.event.inputs.version }}" \
                       --head "release/${{ github.event.inputs.version }}" \
                       --base master \
                       --reviewer ${{ github.actor }} \
                       --body "Hi @${{ github.actor }}!
                              This PR is for ${{ github.event.inputs.version }} release."

      - uses: actions/checkout@v2
        with:
          ref: "release/${{ github.event.inputs.version }}"

      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Release Package Preparation
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "version": "${{ github.event.inputs.version }}", "is_rc": "false" }'
