name: Pull Request Stats

on:
 schedule:
  - cron: "* * * * *"

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
